# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 871, 39))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.storeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.storeButton.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(18)
        self.storeButton.setFont(font)
        self.storeButton.setAccessibleName("")
        self.storeButton.setObjectName("storeButton")
        self.horizontalLayout.addWidget(self.storeButton)
        self.addButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addButton.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(18)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.profileButton = QtWidgets.QPushButton(self.layoutWidget)
        self.profileButton.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(18)
        self.profileButton.setFont(font)
        self.profileButton.setObjectName("profileButton")
        self.horizontalLayout.addWidget(self.profileButton)
        self.statisticButton = QtWidgets.QPushButton(self.layoutWidget)
        self.statisticButton.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(18)
        self.statisticButton.setFont(font)
        self.statisticButton.setObjectName("statisticButton")
        self.horizontalLayout.addWidget(self.statisticButton)
        self.outButton = QtWidgets.QPushButton(self.layoutWidget)
        self.outButton.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(18)
        self.outButton.setFont(font)
        self.outButton.setObjectName("outButton")
        self.horizontalLayout.addWidget(self.outButton)
        self.verticalLayout.addWidget(self.widget)
        self.ViewField = QtWidgets.QWidget(self.centralwidget)
        self.ViewField.setEnabled(True)
        self.ViewField.setAccessibleName("")
        self.ViewField.setObjectName("ViewField")
        self.InfoField = QtWidgets.QGroupBox(self.ViewField)
        self.InfoField.setGeometry(QtCore.QRect(250, 140, 351, 291))
        self.InfoField.setObjectName("InfoField")
        self.verticalLayout.addWidget(self.ViewField)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.storeButton.setText(_translate("MainWindow", "Store"))
        self.addButton.setText(_translate("MainWindow", "Add algorithm"))
        self.profileButton.setText(_translate("MainWindow", "My profile"))
        self.statisticButton.setText(_translate("MainWindow", "Statistics"))
        self.outButton.setText(_translate("MainWindow", "Sign out"))
        self.InfoField.setTitle(_translate("MainWindow", "GroupBox"))
