# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewAlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(567, 453)
        self.addButton = QtWidgets.QPushButton(GroupBox)
        self.addButton.setGeometry(QtCore.QRect(460, 410, 91, 31))
        self.addButton.setObjectName("addButton")
        self.nameEdit = QtWidgets.QLineEdit(GroupBox)
        self.nameEdit.setGeometry(QtCore.QRect(100, 10, 451, 31))
        self.nameEdit.setObjectName("nameEdit")
        self.descEdit = QtWidgets.QLineEdit(GroupBox)
        self.descEdit.setGeometry(QtCore.QRect(100, 50, 451, 31))
        self.descEdit.setObjectName("descEdit")
        self.label = QtWidgets.QLabel(GroupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(GroupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.codeEdit = QtWidgets.QPlainTextEdit(GroupBox)
        self.codeEdit.setGeometry(QtCore.QRect(10, 130, 541, 271))
        self.codeEdit.setObjectName("codeEdit")
        self.label_3 = QtWidgets.QLabel(GroupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.langBox = QtWidgets.QComboBox(GroupBox)
        self.langBox.setGeometry(QtCore.QRect(100, 90, 69, 31))
        self.langBox.setObjectName("langBox")
        self.langBox.addItem("")
        self.langBox.addItem("")

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        self.addButton.setText(_translate("GroupBox", "Add"))
        self.label.setText(_translate("GroupBox", "Name"))
        self.label_2.setText(_translate("GroupBox", "Description"))
        self.label_3.setText(_translate("GroupBox", "Language"))
        self.langBox.setItemText(0, _translate("GroupBox", "Unknown"))
        self.langBox.setItemText(1, _translate("GroupBox", "C++"))
