# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\NewAlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(592, 506)
        self.gridLayout = QtWidgets.QGridLayout(GroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.codeEdit = QtWidgets.QPlainTextEdit(GroupBox)
        self.codeEdit.setObjectName("codeEdit")
        self.gridLayout.addWidget(self.codeEdit, 4, 0, 1, 4)
        self.addButton = QtWidgets.QPushButton(GroupBox)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 5, 3, 1, 1)
        self.langBox = QtWidgets.QComboBox(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        self.langBox.setFont(font)
        self.langBox.setObjectName("langBox")
        self.langBox.addItem("")
        self.langBox.addItem("")
        self.gridLayout.addWidget(self.langBox, 3, 1, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.nameEdit.setFont(font)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.descEdit = QtWidgets.QLineEdit(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.descEdit.setFont(font)
        self.descEdit.setObjectName("descEdit")
        self.gridLayout.addWidget(self.descEdit, 1, 1, 1, 3)
        self.label_4 = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.costEdit = QtWidgets.QLineEdit(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.costEdit.setFont(font)
        self.costEdit.setObjectName("costEdit")
        self.gridLayout.addWidget(self.costEdit, 2, 1, 1, 3)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        self.label.setText(_translate("GroupBox", "Name"))
        self.label_3.setText(_translate("GroupBox", "Language"))
        self.addButton.setText(_translate("GroupBox", "Add"))
        self.langBox.setItemText(0, _translate("GroupBox", "Unknown"))
        self.langBox.setItemText(1, _translate("GroupBox", "C++"))
        self.label_2.setText(_translate("GroupBox", "Description"))
        self.label_4.setText(_translate("GroupBox", "Cost"))
