# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\Purchase.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(479, 408)
        self.gridLayout = QtWidgets.QGridLayout(GroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.Title = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.gridLayout.addWidget(self.Title, 0, 0, 1, 1)
        self.Price = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(10)
        self.Price.setFont(font)
        self.Price.setObjectName("Price")
        self.gridLayout.addWidget(self.Price, 1, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(GroupBox)
        self.nameEdit.setReadOnly(True)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 1, 1, 2)
        self.priceEdit = QtWidgets.QLineEdit(GroupBox)
        self.priceEdit.setReadOnly(True)
        self.priceEdit.setObjectName("priceEdit")
        self.gridLayout.addWidget(self.priceEdit, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(GroupBox)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("UI\\dollar.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.BuyButton = QtWidgets.QPushButton(GroupBox)
        self.BuyButton.setObjectName("BuyButton")
        self.gridLayout.addWidget(self.BuyButton, 5, 1, 1, 2, QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.CancelButton = QtWidgets.QPushButton(GroupBox)
        self.CancelButton.setObjectName("CancelButton")
        self.gridLayout.addWidget(self.CancelButton, 5, 0, 1, 1)
        self.status = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.status.setFont(font)
        self.status.setText("")
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 2, 0, 1, 3)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        self.Title.setText(_translate("GroupBox", "Name: "))
        self.Price.setText(_translate("GroupBox", "Price: "))
        self.BuyButton.setText(_translate("GroupBox", "BUY"))
        self.CancelButton.setText(_translate("GroupBox", "Cancel"))
