# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Store.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(567, 453)
        self.findButton = QtWidgets.QPushButton(GroupBox)
        self.findButton.setGeometry(QtCore.QRect(470, 20, 91, 31))
        self.findButton.setObjectName("findButton")
        self.findEdit = QtWidgets.QLineEdit(GroupBox)
        self.findEdit.setGeometry(QtCore.QRect(10, 20, 451, 31))
        self.findEdit.setObjectName("findEdit")
        self.listWidget = QtWidgets.QListWidget(GroupBox)
        self.listWidget.setGeometry(QtCore.QRect(10, 80, 131, 361))
        self.listWidget.setObjectName("listWidget")
        self.errorLabel = QtWidgets.QLabel(GroupBox)
        self.errorLabel.setGeometry(QtCore.QRect(10, 50, 541, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.errorLabel.setFont(font)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.codeBrowser = QtWidgets.QTextBrowser(GroupBox)
        self.codeBrowser.setGeometry(QtCore.QRect(160, 160, 401, 241))
        self.codeBrowser.setObjectName("codeBrowser")
        self.descInfo = QtWidgets.QLineEdit(GroupBox)
        self.descInfo.setGeometry(QtCore.QRect(160, 80, 401, 31))
        self.descInfo.setReadOnly(True)
        self.descInfo.setObjectName("descInfo")
        self.label = QtWidgets.QLabel(GroupBox)
        self.label.setGeometry(QtCore.QRect(310, 60, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(GroupBox)
        self.label_2.setGeometry(QtCore.QRect(160, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.langInfo = QtWidgets.QLineEdit(GroupBox)
        self.langInfo.setGeometry(QtCore.QRect(230, 120, 61, 31))
        self.langInfo.setReadOnly(True)
        self.langInfo.setObjectName("langInfo")
        self.label_3 = QtWidgets.QLabel(GroupBox)
        self.label_3.setGeometry(QtCore.QRect(340, 120, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.authorInfo = QtWidgets.QLineEdit(GroupBox)
        self.authorInfo.setGeometry(QtCore.QRect(390, 120, 171, 31))
        self.authorInfo.setReadOnly(True)
        self.authorInfo.setObjectName("authorInfo")
        self.getButton = QtWidgets.QPushButton(GroupBox)
        self.getButton.setGeometry(QtCore.QRect(470, 410, 91, 31))
        self.getButton.setObjectName("getButton")

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        self.findButton.setText(_translate("GroupBox", "Find"))
        self.label.setText(_translate("GroupBox", "Description"))
        self.label_2.setText(_translate("GroupBox", "Language"))
        self.label_3.setText(_translate("GroupBox", "Author"))
        self.getButton.setText(_translate("GroupBox", "Get"))
