# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\Store.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(923, 623)
        self.gridLayout = QtWidgets.QGridLayout(GroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.errorLabel = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.errorLabel.setFont(font)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.gridLayout.addWidget(self.errorLabel, 1, 0, 1, 6)
        self.findEdit = QtWidgets.QLineEdit(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(12)
        self.findEdit.setFont(font)
        self.findEdit.setObjectName("findEdit")
        self.gridLayout.addWidget(self.findEdit, 0, 0, 1, 5)
        self.findButton = QtWidgets.QPushButton(GroupBox)
        self.findButton.setObjectName("findButton")
        self.gridLayout.addWidget(self.findButton, 0, 5, 1, 1)
        self.langInfo = QtWidgets.QLineEdit(GroupBox)
        self.langInfo.setReadOnly(True)
        self.langInfo.setObjectName("langInfo")
        self.gridLayout.addWidget(self.langInfo, 5, 2, 1, 1)
        self.authorInfo = QtWidgets.QLineEdit(GroupBox)
        self.authorInfo.setReadOnly(True)
        self.authorInfo.setObjectName("authorInfo")
        self.gridLayout.addWidget(self.authorInfo, 5, 4, 1, 2)
        self.label_3 = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 3, 1, 1)
        self.getButton = QtWidgets.QPushButton(GroupBox)
        self.getButton.setObjectName("getButton")
        self.gridLayout.addWidget(self.getButton, 7, 5, 1, 1)
        self.codeBrowser = QtWidgets.QTextBrowser(GroupBox)
        self.codeBrowser.setObjectName("codeBrowser")
        self.gridLayout.addWidget(self.codeBrowser, 6, 1, 1, 5)
        self.listWidget = QtWidgets.QListWidget(GroupBox)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 4, 0, 4, 1)
        self.descInfo = QtWidgets.QLineEdit(GroupBox)
        self.descInfo.setReadOnly(True)
        self.descInfo.setObjectName("descInfo")
        self.gridLayout.addWidget(self.descInfo, 4, 1, 1, 5)
        self.label_2 = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(GroupBox)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        self.findButton.setText(_translate("GroupBox", "Find"))
        self.label_3.setText(_translate("GroupBox", "Author"))
        self.getButton.setText(_translate("GroupBox", "Get"))
        self.label_2.setText(_translate("GroupBox", "Language"))
        self.label.setText(_translate("GroupBox", "Description"))
