name: Check

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install linter
      run: python -m pip install flake8
    - name: Run linter
      run: python -m flake8 --max-line-length 120 --show-source
  run_tests_unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.2
    - name: Install requirements.txt
      run: python -m pip install -r requirements.txt
    - name: Run tests
      run: python manage.py test
  run_tests_pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.2
    - name: Install requirements.txt
      run: python -m pip install -r requirements.txt
    - name: Run tests
      run: pytest --html=report.html
    - name: Publish report
      uses: actions/upload-artifact@v2
      with:
        name: pytest-report
        path: |
          report.html
          assets/style.css
        retention-days: 60
  run_tests_pytest_with_web_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.2
    - name: Install requirements.txt
      run: python -m pip install -r requirements.txt
    - name: Run server in the background
      run: nohup python manage.py runserver &
    - name: Run tests
      run: pytest --html=report.html --enable_selenium
    - name: Publish report
      uses: actions/upload-artifact@v2
      with:
        name: pytest-report-including-web-tests
        path: |
          report.html
          assets/style.css
        retention-days: 60
