name: Periodic

on:
  schedule:
    - cron: '0 0/4 * * *'

jobs:
  run_tests_pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.2
    - name: Install requirements.txt
      run: python -m pip install -r requirements.txt
    - name: Run tests
      run: pytest --html=report.html -v -m "not web_test"
    - name: Publish report
      uses: actions/upload-artifact@v2
      with:
        name: pytest-report
        path: |
          report.html
          assets/style.css
        retention-days: 30
